### ISSUE TITLE
megjeleno adatok korlatozasa es szurese

### ISSUE THREAD

**Issue by READYonHub** [READYonHub/socca-hungary-teszt#2]
a ki listázott adatok jelenjenek meg 10,25,50,100-as feloszasban és lehessen szűrni nagság szerint bután sorszámszerűen az aktuálisan kilistázott adatokat

**Comment by adiiwill** [comment]
Ez talán jó lehet:
https://datatables.net/

**Comment by READYonHub** [comment]
a stilust megvaltoztattam a dataTablesnél, nem látok logika sem stilus hibát, ha nem találsz te sem semmit, akkor zárd le ezt az issue-t.
